
import type { RegistryComponent } from "./registry.js";

export const nextGenRegistryComponents: RegistryComponent[] = [
  {
    name: "confidence-calibrator",
    title: "ConfidenceCalibrator",
    description: "Pre/post quiz self-rating surface that exposes confidence gaps before review.",
    ai: false,
  },
  {
    name: "mistake-notebook",
    title: "MistakeNotebook",
    description: "Personal error log that resurfaces wrong answers for re-study and coaching.",
    ai: false,
  },
  {
    name: "concept-map-builder",
    title: "ConceptMapBuilder",
    description: "Freeform node-link planning surface for learner-generated knowledge maps.",
    ai: false,
  },
  {
    name: "learning-velocity-chart",
    title: "LearningVelocityChart",
    description: "Time-series view of how quickly concepts are being acquired across a course.",
    ai: false,
  },
  {
    name: "error-pattern-analyzer",
    title: "ErrorPatternAnalyzer",
    description: "Clusters repeated wrong answers into misconception groups that teams can address.",
    ai: false,
  },
  {
    name: "competency-matrix",
    title: "CompetencyMatrix",
    description: "Skills-by-proficiency matrix with evidence drill-down for each competency.",
    ai: false,
  },
  {
    name: "pre-post-test-comparison",
    title: "PrePostTestComparison",
    description: "Side-by-side unit view that compares knowledge before instruction and after mastery work.",
    ai: false,
  },
  {
    name: "parent-progress-digest",
    title: "ParentProgressDigest",
    description: "Weekly summary card that packages activity, effort, and scores into a family-ready digest.",
    ai: false,
  },
  {
    name: "guardian-notification-center",
    title: "GuardianNotificationCenter",
    description: "Threshold-based alert center for grades, absences, overdue work, and support follow-ups.",
    ai: false,
  },
  {
    name: "home-activity-suggester",
    title: "HomeActivitySuggester",
    description: "Curated offline exercises families can do together to reinforce classroom learning.",
    ai: false,
  },
  {
    name: "blooms-taxonomy-tagger",
    title: "BloomsTaxonomyTagger",
    description: "Labels learning objectives across remember-to-create levels with curriculum-ready consistency.",
    ai: false,
  },
  {
    name: "curriculum-drag-builder",
    title: "CurriculumDragBuilder",
    description: "Sequencing surface for arranging modules and lessons into a coherent learning arc.",
    ai: false,
  },
  {
    name: "content-readability-meter",
    title: "ContentReadabilityMeter",
    description: "Flesch-Kincaid inspired readability surface for previewing text difficulty before publishing.",
    ai: false,
  },
  {
    name: "learning-objective-editor",
    title: "LearningObjectiveEditor",
    description: "Structured planning surface for writing SMART objectives and aligning success criteria.",
    ai: false,
  },
  {
    name: "vocab-flash-deck",
    title: "VocabFlashDeck",
    description: "Paired vocabulary flip deck with L1/L2 cues, quick audio affordances, and picture-ready copy.",
    ai: false,
  },
  {
    name: "sentence-constructor",
    title: "SentenceConstructor",
    description: "Word-tile practice surface for assembling grammatically correct sentence order.",
    ai: false,
  },
  {
    name: "pronunciation-scorer",
    title: "PronunciationScorer",
    description: "Waveform-inspired scoring card with phoneme-level feedback for spoken practice.",
    ai: false,
  },
  {
    name: "bilingual-text-toggle",
    title: "BilingualTextToggle",
    description: "Paragraph-level language switch that supports scaffolded reading across two texts.",
    ai: false,
  },
  {
    name: "mood-check-in",
    title: "MoodCheckIn",
    description: "Session-start emotional check-in that logs learner mood and surfaces support needs early.",
    ai: false,
  },
  {
    name: "burnout-risk-indicator",
    title: "BurnoutRiskIndicator",
    description: "Engagement signal composite that flags overload trends before learners disengage.",
    ai: false,
  },
  {
    name: "focus-timer",
    title: "FocusTimer",
    description: "Pomodoro-style work and break planner with quick visibility into distractions and recovery.",
    ai: false,
  },
  {
    name: "wellness-nudge",
    title: "WellnessNudge",
    description: "Contextual micro-tip card that nudges learners to stretch, hydrate, breathe, or reset.",
    ai: false,
  },
  {
    name: "study-group-finder",
    title: "StudyGroupFinder",
    description: "Learner matching surface that organizes study partners by topic, timezone, and availability.",
    ai: false,
  },
  {
    name: "collaborative-notepad",
    title: "CollaborativeNotepad",
    description: "Shared lesson-scoped notes surface with visible contributions and easy synthesis.",
    ai: false,
  },
  {
    name: "kudos-board",
    title: "KudosBoard",
    description: "Recognition wall where classmates can celebrate helpful actions, persistence, and wins.",
    ai: false,
  },
  {
    name: "proctor-mode-overlay",
    title: "ProctorModeOverlay",
    description: "Fullscreen assessment shell that surfaces focus loss, blur events, and live integrity status.",
    ai: false,
  },
  {
    name: "question-variant-manager",
    title: "QuestionVariantManager",
    description: "Variant planning surface for shuffling question pools and parameter sets per learner seat.",
    ai: false,
  },
  {
    name: "suspicious-activity-log",
    title: "SuspiciousActivityLog",
    description: "Timestamped audit trail for paste events, focus losses, idle gaps, and integrity review notes.",
    ai: false,
  },
  {
    name: "dyslexia-font-toggle",
    title: "DyslexiaFontToggle",
    description: "One-click reading preview that switches to a dyslexia-friendly font and spacing profile.",
    ai: false,
  },
  {
    name: "screen-reader-quiz-adapter",
    title: "ScreenReaderQuizAdapter",
    description: "Linearized quiz presentation with clearer announcements, grouping, and assistive-tech hints.",
    ai: false,
  },
  {
    name: "caption-editor",
    title: "CaptionEditor",
    description: "Editable timed transcript surface for keeping lesson captions accurate and learner-friendly.",
    ai: false,
  },
  {
    name: "portfolio-builder",
    title: "PortfolioBuilder",
    description: "Curated artifact gallery where learners pair project evidence with reflection and growth notes.",
    ai: false,
  },
  {
    name: "digital-transcript",
    title: "DigitalTranscript",
    description: "Verifiable course history view with completion evidence and a shareable signature surface.",
    ai: false,
  },
  {
    name: "skill-endorsement-card",
    title: "SkillEndorsementCard",
    description: "Instructor-signed competency card for showcasing validated skills on learner profiles.",
    ai: false,
  },
  {
    name: "bulk-enrollment-uploader",
    title: "BulkEnrollmentUploader",
    description: "Roster upload surface with field mapping previews, row errors, and quick cleanup guidance.",
    ai: false,
  },
  {
    name: "license-seat-manager",
    title: "LicenseSeatManager",
    description: "Org-level seat dashboard that compares allocation, usage, and remaining capacity at a glance.",
    ai: false,
  },
];
