
export const NEXT_GEN_COMPONENT_USAGE_SNIPPETS = {
  "learning-velocity-chart": "import { LearningVelocityChart, type LearningVelocityPoint } from \"edpear-sdk\";\n\nconst sampleLearningVelocityPoint: LearningVelocityPoint[] = [\n  {\n    \"id\": \"w1\",\n    \"label\": \"Week 1\",\n    \"baseline\": 3,\n    \"current\": 4,\n    \"target\": 5,\n    \"detail\": \"Strong start during onboarding module.\"\n  },\n  {\n    \"id\": \"w2\",\n    \"label\": \"Week 2\",\n    \"baseline\": 4,\n    \"current\": 6,\n    \"target\": 5,\n    \"detail\": \"Practice volume pushed velocity above target.\"\n  },\n  {\n    \"id\": \"w3\",\n    \"label\": \"Week 3\",\n    \"baseline\": 6,\n    \"current\": 5,\n    \"target\": 6,\n    \"detail\": \"A harder unit slowed acquisition slightly.\"\n  }\n];\n\n// 1) Default out-of-the-box experience\n<LearningVelocityChart />\n\n// 2) Product data and callbacks\n<LearningVelocityChart\n  points={sampleLearningVelocityPoint}\n  onSelectPoint={(point) => console.log(point.label)}\n  title=\"Workspace view\"\n/>\n\n// 3) Embedded or read-only preview\n<LearningVelocityChart\n  disabled\n  points={sampleLearningVelocityPoint}\n  subtitle=\"Use the built-in structure as a compact embedded panel.\"\n/>",

  "mistake-notebook": "import { MistakeNotebook, type MistakeNotebookEntry } from \"edpear-sdk\";\n\nconst sampleMistakeNotebookEntry: MistakeNotebookEntry[] = [\n  {\n    \"id\": \"m1\",\n    \"title\": \"Confused independent and dependent variables\",\n    \"subtitle\": \"Algebra checkpoint\",\n    \"detail\": \"Learner reversed the axis labels on two recent graphing items.\",\n    \"status\": \"repeating\",\n    \"tag\": \"graphing\",\n    \"evidence\": [\n      \"Quiz 3, question 4\",\n      \"Homework set B, item 7\"\n    ],\n    \"score\": 2\n  },\n  {\n    \"id\": \"m2\",\n    \"title\": \"Dropped units during conversions\",\n    \"subtitle\": \"Science lab write-up\",\n    \"detail\": \"Errors appear when moving between grams, milligrams, and kilograms.\",\n    \"status\": \"watch\",\n    \"tag\": \"measurement\",\n    \"evidence\": [\n      \"Lab draft\",\n      \"Mini-quiz on Tuesday\"\n    ],\n    \"score\": 3\n  },\n  {\n    \"id\": \"m3\",\n    \"title\": \"Skipped textual evidence in responses\",\n    \"subtitle\": \"ELA constructed response\",\n    \"detail\": \"The main idea is correct, but the answer lacks citation discipline.\",\n    \"status\": \"urgent\",\n    \"tag\": \"writing\",\n    \"evidence\": [\n      \"Reading response\",\n      \"Practice assessment\"\n    ],\n    \"score\": 4\n  }\n];\n\n// 1) Default out-of-the-box experience\n<MistakeNotebook />\n\n// 2) Product data and callbacks\n<MistakeNotebook\n  entries={sampleMistakeNotebookEntry}\n  onResurfaceEntry={(entry) => console.log(entry.title)}\n  title=\"Workspace view\"\n/>\n\n// 3) Embedded or read-only preview\n<MistakeNotebook\n  disabled\n  entries={sampleMistakeNotebookEntry}\n  subtitle=\"Use the built-in structure as a compact embedded panel.\"\n/>",

  "bilingual-text-toggle": "import { BilingualTextToggle, type BilingualParagraphVariant } from \"edpear-sdk\";\n\nconst sampleBilingualParagraphVariant: BilingualParagraphVariant[] = [\n  {\n    \"id\": \"l1\",\n    \"label\": \"English\",\n    \"headline\": \"Water cycle overview\",\n    \"body\": \"Evaporation, condensation, and precipitation move water through the environment.\",\n    \"note\": \"Best for independent comprehension checks.\"\n  },\n  {\n    \"id\": \"l2\",\n    \"label\": \"Spanish\",\n    \"headline\": \"Resumen del ciclo del agua\",\n    \"body\": \"La evaporacion, la condensacion y la precipitacion mueven el agua por el ambiente.\",\n    \"note\": \"Use during scaffolded rereads or home support.\"\n  },\n  {\n    \"id\": \"l3\",\n    \"label\": \"Side-by-side\",\n    \"headline\": \"Dual-language compare\",\n    \"body\": \"Display both paragraphs together to support vocabulary transfer and annotation.\",\n    \"note\": \"Helpful for partner reading.\"\n  }\n];\n\n// 1) Default out-of-the-box experience\n<BilingualTextToggle />\n\n// 2) Product data and callbacks\n<BilingualTextToggle\n  variants={sampleBilingualParagraphVariant}\n  onVariantChange={(variantId) => console.log(variantId)}\n  title=\"Workspace view\"\n/>\n\n// 3) Embedded or read-only preview\n<BilingualTextToggle\n  disabled\n  variants={sampleBilingualParagraphVariant}\n  subtitle=\"Use the built-in structure as a compact embedded panel.\"\n/>",

  "sentence-constructor": "import { SentenceConstructor, type SentenceTile } from \"edpear-sdk\";\n\nconst sampleSentenceTile: SentenceTile[] = [\n  {\n    \"id\": \"s1\",\n    \"title\": \"First\",\n    \"detail\": \"drag starter\",\n    \"tag\": \"capitalized\"\n  },\n  {\n    \"id\": \"s2\",\n    \"title\": \"the learner\",\n    \"detail\": \"subject chunk\",\n    \"tag\": \"subject\"\n  },\n  {\n    \"id\": \"s3\",\n    \"title\": \"checks the evidence.\",\n    \"detail\": \"verb phrase\",\n    \"tag\": \"predicate\"\n  }\n];\n\n// 1) Default out-of-the-box experience\n<SentenceConstructor />\n\n// 2) Product data and callbacks\n<SentenceConstructor\n  tiles={sampleSentenceTile}\n  onSaveTiles={(items) => console.log(items.length)}\n  title=\"Workspace view\"\n/>\n\n// 3) Embedded or read-only preview\n<SentenceConstructor\n  disabled\n  tiles={sampleSentenceTile}\n  subtitle=\"Use the built-in structure as a compact embedded panel.\"\n/>",
} as const;
